env:
  browser: true
  es2021: true
extends: 
  - airbnb
  - airbnb/hooks
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended
overrides:
  - env:
      node: true
    files:
      - '.eslintrc.{js,cjs}'
    parserOptions:
      sourceType: script
parserOptions:
  ecmaVersion: latest
  sourceType: module
